[package]
name = "bellman-cuda-cudart"
version = "0.0.0"
edition = "2021"

[dependencies]
bellman-cuda-cudart-sys = { path = "../cudart-sys" }
bitflags = "1.3"

[dev-dependencies]
serial_test = "0.7"
